name: my_project
version: '1.0.0'
config-version: 2

# Set the profile to use for this project
profile: my_dbt_profile

# Define your sources and their associated directories

# Set the schema that your models will be created in
# Replace 'my_schema' with the name of your target schema
# Note that this schema will be created automatically by dbt
# if it doesn't already exist
models:
  my_schema:
    # Set the materialization method to use for all models
    # Replace 'snowflake' with the name of your database type
    # and 'view' with the type of materialization you want to use
    # Other options include 'table', 'ephemeral', 'incremental', etc.
    materialized: view
    # Set the database where your models will be created
    # Replace 'my_database' with the name of your target database
    database: my_database
